apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-tests
spec:
  steps:
    - name: run-nose-tests
      image: python:3.9
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        pip install -r requirements.txt
        pip install nose
        nosetests tests/

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: delete-temp-files
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning up temporary files..."
        rm -rf /workspace/source/tmp
